### ISSUE TITLE
Supporting WebAssembly

### ISSUE THREAD

**Issue by chrispahm** [GAMS-dev/gams-cpp#10]
Hey there!
First off, thanks for your amazing work on the C++ API and GAMS in general!

In the past, we had several issues with reading GDX containers through the higher level APIs (mostly `gdxrrw` and a missing link to a GAMS installation in R).
As all of these issues were related to software setup (no actual GAMS/GAMS API issues), we had a further look into container solutions (e.g. docker). However, especially when working with students or project partners not too familiar with the matter, setting up theses containers is still cumbersome. 

As a possible solution, I was thinking about creating a WebAssembly module for reading GDX containers. In my opinion, there are many benefits from being able to read GDX containers in browsers. It would a very portable solution, and would not require any installation for users who would just like to explore model results or do follow up statistics despite not being modelers themselves. Also, I guess the GAMS MIRO project could benefit from a WebAssembly GDX module as well.

As a start, I tried to compile the xp_example1 to WebAssembly using [emscripten](https://emscripten.org/). However, as stated in the README of this repo, the C++ API requires the low level APIs provided by the GAMS distribution packages. As these require some dynamic linked libraries ([being unsupported by WebAssembly](https://floooh.github.io/2017/06/09/webassembly-demystified.html#can-i-load-and-call-into-a-dll-from-webassembly)), the conversion failed. 

My knowledge about the matter is absolutely limited, so excuse me if any of the questions are stupid:
a) would it be possible to replace the linked libraries with their "original, non-machine code", or is there any other alternative that you know of that I could use?
b) do you have any plans for porting the library to WebAssembly in general?

Best
Christoph

**Comment by LutzWestermann** [comment]
Hi Christoph,

We have nothing in place for this right now. Though, we are in the progress of preparing a version of the GDX library to be released as open source. Would this be interesting for you? This might still take a while to be completed, but if this is of interest for your project, please drop a note to support@gams.com. We might give you an early access to this.

Best,
Lutz

**Comment by chrispahm** [comment]
Thank you for your reply! The open source version will indeed be of interest for the project. I will write a short Mail to the given address 😊

**Comment by LutzWestermann** [comment]
Christoph, I believe, in this thread we cannot offer any more, so I'll close it. Please reopen if you disagree.

**Comment by chrispahm** [comment]
Hi @LutzWestermann, are there any updates on the open source GDX version?

**Comment by LutzWestermann** [comment]
@chrispahm , sorry to give you the answer you probably heard already years ago, but we are not there yet...
We are actually much further than 3 years ago, making most of the progress within the last 6 months, but are still in an intermediate state. I do not want to give promises here, but if I would, I would mention a publication later this year

**Comment by LutzWestermann** [comment]
> Hi @LutzWestermann, are there any updates on the open source GDX version?

@chrispahm , it was [published](https://github.com/GAMS-dev/gdx) just today! :)
